"""Compiles and runs the code generated by the Part 3 LLM run against our shared test cases.

The generated files in generated_code/ are used exactly as the LLM wrote them (no edits).
Run from the B5 folder:   python Part3/llm/test_generated_code.py
Writes Part3/llm/generated_code_test.log
"""
import datetime
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.join("Part3", "llm", "generated_code")
CASES = os.path.abspath(os.path.join("Part3", "test-cases"))
PROGRAMS = [
    ("document_page", "document_page_cases.txt", "DocumentPageTest"),
    ("upload_check", "upload_check_cases.txt", "UploadCheckTest"),
]

log = ["Test of the code generated by the Part 3 LLM run (output.md) against our shared test cases.",
       f"Date (UTC): {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%dT%H:%M:%SZ} | Windows 11 | Java 25, "
       "CPython 3.11.9, Node.js v24.17.0, clang 21.1.0 (ziglang 0.16.0)",
       "The generated files were compiled and run without any edit; the case file is the first argument."]
for problem, cases, java_class in PROGRAMS:
    case_file = os.path.join(CASES, cases)
    for language in ["java", "python", "javascript", "cpp"]:
        folder = os.path.join(HERE, problem, language)
        build = tempfile.mkdtemp()
        if language == "java":
            steps = [["javac", "-d", build, java_class + ".java"], ["java", "-cp", build, java_class, case_file]]
        elif language == "python":
            steps = [[sys.executable, problem + ".py", case_file]]
        elif language == "javascript":
            steps = [["node", problem + ".js", case_file]]
        else:
            exe = os.path.join(build, problem + ".exe")
            steps = [[sys.executable, "-m", "ziglang", "c++", "-std=c++17", "-O2", "-o", exe, problem + ".cpp"],
                     [exe, case_file]]
        log.append(f"\n=== {problem} / {language}")
        for step in steps:
            shown = [os.path.basename(part) if os.sep in part else part for part in step]
            result = subprocess.run(step, cwd=folder, capture_output=True, text=True)
            log += ["$ " + " ".join(shown), (result.stdout + result.stderr).rstrip(), f"exit code: {result.returncode}"]
            if result.returncode:
                break
        shutil.rmtree(build, ignore_errors=True)
        print(problem, language, [line for line in log[-2].splitlines() if line.startswith("passed")] or log[-2][-200:])

with open(os.path.join("Part3", "llm", "generated_code_test.log"), "w", encoding="utf-8") as f:
    f.write("\n".join(log) + "\n")
